const screens = {
  research: `<div class="screen-inner"><div class="screen-head"><div><h2>Deep legal research</h2><p>Source-backed research with explicit legitimate-domain filtering.</p></div><button class="outline small" data-toast="Research cancelled">× Cancel</button></div><div class="notice"><b>✓ Searching only:</b> .gov, .edu, court sites, bar associations, legal publishers</div><div class="research-step"><div class="step-top"><span>01</span><b>Planning your query…</b><span class="step-status done">Complete</span></div><div class="bar"><span style="width:100%"></span></div></div><div class="research-step"><div class="step-top"><span>02</span><b>Searching legitimate legal sources…</b><span class="step-status progress">In progress</span></div><div class="bar"><span style="width:66%"></span></div><div class="step-detail">Whitelist: legislation.gov.uk · supremecourt.uk · bailii.org</div></div><div class="research-step"><div class="step-top"><span>03</span><b>Reading and analyzing…</b><span class="step-status">Queued</span></div><div class="bar"><span style="width:25%"></span></div><div class="step-detail">3 sources discovered</div></div><div class="research-step"><div class="step-top"><span>04</span><b>Writing report…</b><span class="step-status">Queued</span></div><div class="bar"><span style="width:8%"></span></div></div><div class="assistant-card"><div class="assistant-head"><div class="mini-mark">C</div><b>Research result</b><span class="privacy-text local">Citations attached</span></div><p>The final report will appear here as source-backed text streams in. A Sources section remains attached to the report for audit and review.</p></div></div>`,
  documents: `<div class="document-shell"><div class="template-bar"><span>Template</span><button class="chip">Non-Disclosure Agreement</button><button class="chip">Employment Contract</button><button class="chip active">Legal Memo</button><button class="chip">Motion</button><button class="chip">Letter</button><button class="chip">Edit</button><button class="chip">Preview</button><button class="chip active">Split</button></div><div class="doc-body"><div class="mdx-pane"><div class="eyebrow">MDX</div><div class="codebox">01  # LEGAL MEMORANDUM\n02\n03  ## To\n04  Managing Partner\n05\n06  ## From\n07  Counsel AI\n08\n09  ## Re: Breach of Contract Remedies\n10\n11  ### Issue\n12  What remedies may be available following a material breach?\n13\n14  ### Summary\n15  The answer depends on the contractual terms and\n16  the legal classification of the breach.\n17\n18  ### Analysis\n19  A repudiatory breach may entitle the innocent party\n20  to accept the repudiation and terminate. Damages\n21  remain subject to ordinary principles of causation,\n22  remoteness and mitigation.\n23\n24  &lt;!-- Select text to regenerate this section --&gt;</div></div><div class="preview-pane"><div class="paper"><h1>LEGAL MEMORANDUM</h1><p>To: Managing Partner<br>From: Counsel AI<br>Re: Breach of Contract Remedies</p><h3>Issue</h3><p>What remedies may be available following a material breach?</p><h3>Analysis</h3><p>The contractual terms should be reviewed first. A repudiatory breach may permit termination, while damages remain subject to ordinary principles of causation, remoteness and mitigation. The report should be read with the cited authorities before client advice is issued.</p><button class="outline small" data-toast="Section queued for regeneration">↻ Regenerate section</button></div></div></div><footer class="doc-footer"><span class="jurisdiction">Drafted under: England & Wales law</span><button data-toast="Copied">Copy</button><button data-toast="Duplicated">Duplicate</button><button data-toast="PDF export prepared">Export PDF</button><button class="primary" data-toast="DOCX export prepared">Export DOCX</button></footer></div>`,
  settings: `<div class="settings"><h2>Settings</h2><p>Plain-English controls. Nothing here requires technical knowledge.</p>${settingsCard('Model','Choose how Counsel AI generates answers.',[['Local model','Runs on this computer. Private by default.','Llama 3.1 8B · GGUF'],['VRAM usage','Current memory used by the local model.','4.2 GB / 8 GB'],['Context length','How much text can be considered at once.','16k tokens'],['Temperature','Lower values produce more consistent drafting.','0.2']])}${settingsCard('Privacy','Control what stays on this device and what may leave it.',[['Data retention','Keep conversation history locally for later review.','ON'],['Encryption','Local app data is stored with encryption enabled.','Enabled'],['Cloud AI warning','Warn before confidential material is sent to an external API.','ON'],['Clear local data','Permanently remove local conversations and cached files.','Clear all data']])}${settingsCard('Search filters','Choose which sources Research mode may use.',[['Default legitimate sources','.gov, .edu, court sites, bar associations, legal publishers','Active'],['Custom whitelist','Add trusted domains that your firm uses.','Manage domains']])}${settingsCard('Tools','Connect external services only when you approve them.',[['Gmail','Send email only after preview and confirmation.','Connect'],['Outlook','Use Microsoft 365 email and calendar.','Connect'],['Calendar','Create events only after you approve the details.','Connect']])}${settingsCard('Appearance','Keep the legal-office look you find easiest to read.',[['Dark mode','Optional. Light mode is the default.','OFF'],['Text size','Adjust interface text for comfortable reading.','100%'],['Keyboard shortcuts','Ctrl+K · Ctrl+N · Ctrl+S · Ctrl+/','View all']])}</div>`
};
function settingsCard(title,help,rows){return `<section class="settings-card"><h3>${title}</h3><p>${help}</p>${rows.map((r,i)=>`<div class="setting-row"><div><b>${r[0]}</b><small>${r[1]}</small></div>${buttonFor(r[2])}</div>`).join('')}</section>`}
function buttonFor(v){if(['Connect','Manage domains','View all'].includes(v)) return `<button class="outline small" data-toast="${v} opened">${v}</button>`;if(v==='Clear all data') return `<button class="danger" data-toast="Confirmation required before clearing data">${v}</button>`;if(v==='Enabled'||v==='Active') return `<span class="badge">${v}</span>`;if(v==='ON') return `<button class="outline small" data-toast="Setting changed">ON</button>`;if(v==='OFF') return `<button class="outline small" data-toast="Setting changed">OFF</button>`;return `<span style="font-size:12px;font-weight:600">${v}</span>`}

let currentScreen='chat';
const titleMap={chat:'Assistant',research:'Deep legal research',documents:'Documents',settings:'Settings'};
function showScreen(name){currentScreen=name;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));if(name==='chat')document.getElementById('view-chat').classList.remove('hidden');else{const v=document.getElementById('view-'+name);v.innerHTML=screens[name];v.classList.remove('hidden')}document.getElementById('pageTitle').textContent=titleMap[name];document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.screen===name));bindDynamic();}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(window._toast);window._toast=setTimeout(()=>el.classList.add('hidden'),1600)}
function bindDynamic(){document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active')})}

document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='collapse'){document.getElementById('sidebar').classList.add('hidden')}if(a==='expand'){document.getElementById('sidebar').classList.remove('hidden')}if(a==='new-chat')toast('New conversation ready')});
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');const m=b.dataset.mode;const n=document.getElementById('privacyNotice');if(m==='api'){n.innerHTML='<span class="dot amber"></span>External API · Review before sending confidential material';n.style.color='#B45309'}else if(m==='local'){n.innerHTML='<span class="dot green"></span>Local mode · Data stays on this device';n.style.color='#047857'}else if(m==='research'){showScreen('research')}else if(m==='tools'){toast('External tools require preview and consent before action')}});
document.getElementById('sourceToggle').onclick=()=>document.getElementById('sources').classList.toggle('hidden');
document.getElementById('darkToggle').onclick=()=>document.body.classList.toggle('dark');
document.querySelector('.send').onclick=()=>toast('Response queued — streaming begins here in the app');
document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>toast('Prompt inserted'));

const ob=document.getElementById('onboarding'), stepEl=document.getElementById('onboardStep'), fill=document.getElementById('progressFill');let step=0;
function renderOnboarding(){fill.style.width=((step+1)*33)+'%';if(step===0){stepEl.innerHTML=`<h1>Private legal help, without the complexity.</h1><p>Counsel AI helps you ask legal questions, research legitimate sources, and draft documents while keeping privacy and citations visible.</p><div class="step-copy"><b>Local-first by design.</b><p>You never need to create an account for the desktop app.</p></div><div class="step-actions"><button class="secondary" id="skip">Skip for demo</button><button class="primary" id="next">Continue</button></div>`}else if(step===1){stepEl.innerHTML=`<h1>Set your jurisdiction</h1><p>We use this to tailor legal answers and document drafting. City is optional.</p><label class="field"><span>Country</span><select><option>United Kingdom</option><option>United States</option><option>Pakistan</option><option>Canada</option></select></label><div class="form-row"><label class="field"><span>Province / State</span><select><option>England & Wales</option><option>Scotland</option><option>Northern Ireland</option></select></label><label class="field"><span>City (optional)</span><input placeholder="e.g. London"></label></div><div class="notice">We'll tailor all legal answers to: <b>United Kingdom, England & Wales</b></div><div class="step-actions"><button class="secondary" id="back">Back</button><button class="primary" id="next">Continue</button></div>`}else{stepEl.innerHTML=`<h1>Choose your privacy mode</h1><p>You can change this later. Local mode is the recommended default for confidential work.</p><label class="privacy-option selected"><input type="radio" checked name="privacy"><div><b>Local / private</b><p>Prompts and files stay on this computer.</p></div></label><label class="privacy-option"><input type="radio" name="privacy"><div><b>Cloud API</b><p>Use a remote AI provider when speed or model choice matters.</p></div></label><div class="step-actions"><button class="secondary" id="back">Back</button><button class="primary" id="start">Get started</button></div>`}document.getElementById('next')?.addEventListener('click',()=>{step++;renderOnboarding()});document.getElementById('back')?.addEventListener('click',()=>{step--;renderOnboarding()});document.getElementById('skip')?.addEventListener('click',()=>ob.classList.add('hidden'));document.getElementById('start')?.addEventListener('click',()=>ob.classList.add('hidden'))}

bindDynamic();renderOnboarding();
// The production product keeps onboarding off once completed; this prototype shows it only on explicit demo start.
