const resultMarkup = (query) => `
<div class="results-shell">
  <div class="results-main">
    <div class="query-pill"><span>⌕</span><span>${escapeHtml(query)}</span><button class="tiny-btn" id="editQuery">Edit</button></div>
    <div class="result-tabs" role="tablist"><button class="result-tab active" data-tab="answer">◫ Answer</button><button class="result-tab" data-tab="links">↗ Links <span>12</span></button><button class="result-tab" data-tab="images">▧ Images <span>8</span></button></div>
    <div id="answerPanel" class="tab-panel">
      <div class="answer-meta"><span>Completed 4 steps</span><span class="research-status"><span class="dot green"></span>Research mode</span></div>
      <article class="answer-card">
        <div class="answer-head"><div class="mini-mark">C</div><div><b>Counsel AI</b><small>Source-backed legal answer</small></div><span class="spacer"></span><span class="privacy-text local">Private · Local</span></div>
        <p>Based on the legitimate legal sources reviewed, a material breach under English law may allow the innocent party to claim damages and, where the breach is repudiatory or the contract provides for it, terminate the contract.</p>
        <h3>Potential remedies</h3>
        <p><b>Damages.</b> The claimant must establish causation and recoverable loss, subject to remoteness and mitigation.</p>
        <p><b>Termination.</b> A sufficiently serious repudiatory breach can permit the innocent party to accept the repudiation and bring the contract to an end.</p>
        <p><b>Specific relief.</b> Specific performance or an injunction may be available in limited cases where damages are inadequate.</p>
        <div class="inline-citation"><span>[1]</span><b>Legislation.gov.uk</b><code>https://www.legislation.gov.uk/</code></div>
        <div class="inline-citation"><span>[2]</span><b>UK Supreme Court</b><code>https://www.supremecourt.uk/</code></div>
        <div class="inline-citation"><span>[3]</span><b>BAILII</b><code>https://www.bailii.org/</code></div>
      </article>
      <div class="sources-heading"><b>Sources</b><span>Legitimate sources only</span></div>
      <div class="source-list">
        <button class="source-row"><span class="source-index">1</span><div><b>Legislation.gov.uk</b><small>legislation.gov.uk</small></div><span class="source-score">High</span><span>›</span></button>
        <button class="source-row"><span class="source-index">2</span><div><b>UK Supreme Court</b><small>supremecourt.uk</small></div><span class="source-score">High</span><span>›</span></button>
        <button class="source-row"><span class="source-index">3</span><div><b>BAILII</b><small>bailii.org</small></div><span class="source-score medium">Medium</span><span>›</span></button>
        <button class="source-row"><span class="source-index">4</span><div><b>Law Commission</b><small>lawcom.gov.uk</small></div><span class="source-score">High</span><span>›</span></button>
      </div>
    </div>
    <div id="linksPanel" class="tab-panel hidden"><div class="panel-intro"><b>Links</b><span>12 legitimate references found</span></div>${Array.from({length:6},(_,i)=>`<a class="link-result" href="#"><span class="link-no">${i+1}</span><div><b>${['Contractual Remedies and Termination','Breach of Contract — Supreme Court materials','Remedies for breach of contract','Commercial Court decisions','Law Commission contract guidance','Civil Procedure resources'][i]}</b><small>${['legislation.gov.uk','supremecourt.uk','bailii.org','judiciary.uk','lawcom.gov.uk','justice.gov.uk'][i]}</small><p>Relevant source material selected by Counsel AI's legitimate-domain filter.</p></div></a>`).join('')}</div>
    <div id="imagesPanel" class="tab-panel hidden"><div class="panel-intro"><b>Images</b><span>8 visual references from trusted legal sources</span></div><div class="image-grid">${Array.from({length:8},(_,i)=>`<button class="image-card" data-toast="Image ${i+1} opened"><div class="image-placeholder"><span>Legal source</span></div><b>${['Contract notice','Court document','Judgment page','Case chronology','Statutory extract','Procedure flow','Practice note','Authority index'][i]}</b><small>${['gov.uk','supremecourt.uk','bailii.org','judiciary.uk'][i%4]}</small></button>`).join('')}</div></div>
    <div class="followup-wrap"><div class="privacy-notice"><span class="dot green"></span>Local mode · Data stays on this device</div><div class="followup"><button class="tool-button">＋</button><textarea id="followupInput" placeholder="Ask a follow-up..."></textarea><button class="search-mode">⌕ Search</button><button class="send" id="followupSend">↑</button></div><div class="followup-foot"><span>Ctrl+K · command palette</span><span>Citations remain visible</span></div></div>
  </div>
  <aside class="sources-rail"><div class="rail-head"><b>Sources</b><span>${sourceCount}</span></div><div class="rail-filter"><span>Legitimate only</span><span class="dot green"></span></div><div class="rail-source"><b>Legislation.gov.uk</b><small>Statutes and legislation</small><code>legislation.gov.uk</code></div><div class="rail-source"><b>UK Supreme Court</b><small>Judgments and case materials</small><code>supremecourt.uk</code></div><div class="rail-source"><b>BAILII</b><small>British and Irish legal information</small><code>bailii.org</code></div><div class="rail-source"><b>Law Commission</b><small>Official consultation material</small><code>lawcom.gov.uk</code></div><button class="rail-more">View all sources</button></aside>
</div>`;

const sourceCount = 12;
const screens = {
  research: `<div class="screen-inner"><div class="screen-head"><div><h2>Deep legal research</h2><p>Research runs separately from the answer so you can see exactly what Counsel AI is doing.</p></div><button class="outline small" data-toast="Research cancelled">× Cancel</button></div><div class="notice"><b>Searching only:</b> .gov, .edu, court sites, bar associations, legal publishers</div><div class="research-step"><div class="step-top"><span>01</span><b>Planning your query…</b><span class="step-status done">Complete</span></div><div class="bar"><span style="width:100%"></span></div></div><div class="research-step"><div class="step-top"><span>02</span><b>Searching legitimate legal sources…</b><span class="step-status progress">In progress</span></div><div class="bar"><span style="width:66%"></span></div><div class="step-detail">Whitelist: legislation.gov.uk · supremecourt.uk · bailii.org · lawcom.gov.uk</div></div><div class="research-step"><div class="step-top"><span>03</span><b>Reading and analyzing…</b><span class="step-status">Queued</span></div><div class="bar"><span style="width:25%"></span></div><div class="step-detail">12 sources discovered · 8 selected as high relevance</div></div><div class="research-step"><div class="step-top"><span>04</span><b>Writing report…</b><span class="step-status">Queued</span></div><div class="bar"><span style="width:8%"></span></div></div></div>`,
  documents: `<div class="document-shell"><div class="template-bar"><span>Template</span><button class="chip">Non-Disclosure Agreement</button><button class="chip">Employment Contract</button><button class="chip active">Legal Memo</button><button class="chip">Motion</button><button class="chip">Letter</button><button class="chip">Edit</button><button class="chip">Preview</button><button class="chip active">Split</button></div><div class="doc-body"><div class="mdx-pane"><div class="eyebrow">MDX</div><div class="codebox">01  # LEGAL MEMORANDUM\n02\n03  ## To\n04  Managing Partner\n05\n06  ## From\n07  Counsel AI\n08\n09  ## Re: Breach of Contract Remedies\n10\n11  ### Issue\n12  What remedies may be available following a material breach?\n13\n14  ### Summary\n15  The answer depends on the contractual terms and\n16  the legal classification of the breach.\n17\n18  ### Analysis\n19  A repudiatory breach may entitle the innocent party\n20  to accept the repudiation and terminate. Damages\n21  remain subject to ordinary principles of causation,\n22  remoteness and mitigation.\n23\n24  &lt;!-- Select text to regenerate this section --&gt;</div></div><div class="preview-pane"><div class="paper"><div class="jurisdiction">Drafted under: England & Wales law</div><h1>LEGAL MEMORANDUM</h1><p>To: Managing Partner<br>From: Counsel AI<br>Re: Breach of Contract Remedies</p><h3>Issue</h3><p>What remedies may be available following a material breach?</p><h3>Analysis</h3><p>The contractual terms should be reviewed first. A repudiatory breach may permit termination, while damages remain subject to ordinary principles of causation, remoteness and mitigation.</p><button class="outline small" data-toast="Section queued for regeneration">↻ Regenerate section</button></div></div></div><footer class="doc-footer"><span class="jurisdiction">Drafted under: England & Wales law</span><button data-toast="Copied">Copy</button><button data-toast="Duplicated">Duplicate</button><button data-toast="PDF export prepared">Export PDF</button><button class="primary" data-toast="DOCX export prepared">Export DOCX</button></footer></div>`,
  settings: `<div class="settings"><h2>Settings</h2><p>Plain-English controls. Nothing here requires technical knowledge.</p>${settingsCard('Model','Choose how Counsel AI generates answers.',[['Local model','Runs on this computer. Private by default.','Llama 3.1 8B · GGUF'],['VRAM usage','Current memory used by the local model.','4.2 GB / 8 GB'],['Context length','How much text can be considered at once.','16k context'],['Temperature','Lower values produce more consistent drafting.','0.2']])}${settingsCard('Privacy','Control what stays on this device and what may leave it.',[['Data retention','Keep conversation history locally for later review.','ON'],['Encryption','Local app data is stored with encryption enabled.','Enabled'],['Cloud AI warning','Warn before confidential material is sent externally.','ON'],['Clear local data','Permanently remove local conversations and cached files.','Clear all data']])}${settingsCard('Search filters','Choose which sources Research mode may use.',[['Default legitimate sources','.gov, .edu, court sites, bar associations, legal publishers','Active'],['Custom whitelist','Add trusted domains that your firm uses.','Manage domains']])}${settingsCard('Tools','Connect external services only when you approve them.',[['Gmail','Send email only after preview and confirmation.','Connect'],['Outlook','Use Microsoft 365 email and calendar.','Connect'],['Calendar','Create events only after you approve the details.','Connect']])}${settingsCard('Appearance','Keep the legal-office look you find easiest to read.',[['Dark mode','Optional. Light mode is the default.','OFF'],['Text size','Adjust interface text for comfortable reading.','100%'],['Keyboard shortcuts','Ctrl+K · Ctrl+N · Ctrl+S · Ctrl+/','View all']])}</div>`
};
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function settingsCard(title,help,rows){return `<section class="settings-card"><h3>${title}</h3><p>${help}</p>${rows.map(r=>`<div class="setting-row"><div><b>${r[0]}</b><small>${r[1]}</small></div>${buttonFor(r[2])}</div>`).join('')}</section>`}
function buttonFor(v){if(['Connect','Manage domains','View all'].includes(v)) return `<button class="outline small" data-toast="${v} opened">${v}</button>`;if(v==='Clear all data') return `<button class="danger" data-toast="Confirmation required before clearing data">${v}</button>`;if(['Enabled','Active'].includes(v)) return `<span class="badge">${v}</span>`;if(['ON','OFF'].includes(v)) return `<button class="outline small" data-toast="Setting changed">${v}</button>`;return `<span class="setting-value">${v}</span>`}

let currentScreen='home';
const titleMap={home:'Counsel AI',results:'Answer',research:'Research',documents:'Documents',settings:'Settings'};
function showScreen(name){currentScreen=name;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));const target=document.getElementById('view-'+name);if(target) target.classList.remove('hidden');if(screens[name]){target.innerHTML=screens[name];bindDynamic();}document.getElementById('pageTitle').textContent=titleMap[name]||'Counsel AI';document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.screen===name));}
function showResults(query){document.getElementById('view-results').innerHTML=resultMarkup(query);showScreen('results');bindResults();}
function runSearch(value){const q=value.trim()||'Show me the key authorities and commentary on breach of contract remedies in England';showResults(q);toast('Research started — legitimate sources only');}
function bindResults(){document.querySelectorAll('.result-tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.result-tab').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.querySelectorAll('.tab-panel').forEach(p=>p.classList.add('hidden'));document.getElementById(tab.dataset.tab+'Panel').classList.remove('hidden');});document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));document.getElementById('followupSend')?.addEventListener('click',()=>runSearch(document.getElementById('followupInput').value));document.getElementById('editQuery')?.addEventListener('click',()=>showScreen('home'));}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(window._toast);window._toast=setTimeout(()=>el.classList.add('hidden'),1600)}
function bindDynamic(){document.querySelectorAll('[data-toast]').forEach(b=>b.onclick=()=>toast(b.dataset.toast));document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active')});}

document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>showScreen(b.dataset.screen));
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='collapse')document.getElementById('sidebar').classList.add('hidden');if(a==='expand')document.getElementById('sidebar').classList.remove('hidden');if(a==='new-chat'){showScreen('home');document.getElementById('queryInput').value='';toast('New conversation ready')}});
document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');const m=b.dataset.mode;if(m==='api')toast('External API · review before sending confidential material');if(m==='local')toast('Local mode · data stays on this device');if(m==='research')showScreen('research');if(m==='tools')toast('External tools require preview and consent before action')});
document.getElementById('searchButton').onclick=()=>runSearch(document.getElementById('queryInput').value);
document.getElementById('queryInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();runSearch(e.target.value)}});
document.querySelectorAll('[data-query]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('queryInput').value=b.dataset.query;runSearch(b.dataset.query)}));
document.getElementById('attachButton').onclick=()=>toast('Drop PDF or DOCX files here');
document.getElementById('darkToggle').onclick=()=>document.body.classList.toggle('dark');

const ob=document.getElementById('onboarding'),stepEl=document.getElementById('onboardStep'),fill=document.getElementById('progressFill');let step=0;
function renderOnboarding(){fill.style.width=((step+1)*33)+'%';if(step===0){stepEl.innerHTML=`<h1>Private legal help, without the complexity.</h1><p>Counsel AI helps you search legitimate sources, ask legal questions, and draft documents while keeping privacy and citations visible.</p><div class="step-copy"><b>Local-first by design.</b><p>No account or email is required for the desktop app.</p></div><div class="step-actions"><button class="secondary" id="skip">Skip for demo</button><button class="primary" id="next">Continue</button></div>`}else if(step===1){stepEl.innerHTML=`<h1>Set your jurisdiction</h1><p>We use this to tailor answers and drafting. City is optional.</p><label class="field"><span>Country</span><select><option>United Kingdom</option><option>United States</option><option>Pakistan</option><option>Canada</option></select></label><div class="form-row"><label class="field"><span>Province / State</span><select><option>England & Wales</option><option>Scotland</option><option>Northern Ireland</option></select></label><label class="field"><span>City (optional)</span><input placeholder="e.g. London"></label></div><div class="notice">We'll tailor all legal answers to: <b>United Kingdom, England & Wales</b></div><div class="step-actions"><button class="secondary" id="back">Back</button><button class="primary" id="next">Continue</button></div>`}else{stepEl.innerHTML=`<h1>Choose your privacy mode</h1><p>Local mode is the recommended default for confidential work.</p><label class="privacy-option selected"><input type="radio" checked name="privacy"><div><b>Local / private</b><p>Prompts and files stay on this computer.</p></div></label><label class="privacy-option"><input type="radio" name="privacy"><div><b>Cloud API</b><p>Use a remote AI provider when speed or model choice matters.</p></div></label><div class="step-actions"><button class="secondary" id="back">Back</button><button class="primary" id="start">Get started</button></div>`}document.getElementById('next')?.addEventListener('click',()=>{step++;renderOnboarding()});document.getElementById('back')?.addEventListener('click',()=>{step--;renderOnboarding()});document.getElementById('skip')?.addEventListener('click',()=>ob.classList.add('hidden'));document.getElementById('start')?.addEventListener('click',()=>ob.classList.add('hidden'))}

bindDynamic();renderOnboarding();
